spring:
    liquibase:
        change-log: classpath:liquibase/master.yml
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver
